---

Metrics/LineLength:
  Max: 155
AllCops:
  SuggestExtensions: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
StringLiterals:
  Enabled: false
Lint/ScriptPermission:
  Enabled: false
Metrics/BlockLength:
  Enabled: false