# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username:
  password:
  pool: 5

development:
  <<: *default
  database: isa_client_test_development

test:
  <<: *default
  database: isa_client_test_test

production:
  <<: *default
  database: isa_client_test_production
  username: isa_client_test
  password: <%= ENV['ISA_CLIENT_TEST_DATABASE_PASSWORD'] %>
