QueueJob.create(name: 'QueueJob1', priority: 'low')
QueueJob.create(name: 'QueueJob2', priority: 'critical')
QueueJob.create(name: 'QueueJob3', priority: 'high')
QueueJob.create(name: 'QueueJob4', priority: 'high')
QueueJob.create(name: 'QueueJob5', priority: 'critical')
